# Generated by Django 6.0.3 on 2026-03-11 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('rooms', '0002_alter_room_capacity_alter_room_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start', 'end'], name='bookings_bo_start_352e72_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'start', 'end'], name='bookings_bo_room_id_ce30f3_idx'),
        ),
    ]
